FROM python:3.10

ENV TZ Asia/Tokyo

WORKDIR /usr/src/app

COPY back/requirements.txt ./

#RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --upgrade pip && \
    pip install -r requirements.txt    

COPY . .
